# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_aud_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
