# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0002_auto_20160803_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_draft',
            field=models.BooleanField(default=True),
        ),
    ]
