# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0003_course_course_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_course', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
