# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0004_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_aud_desc',
            new_name='course_expect_desc',
        ),
        migrations.AddField(
            model_name='course',
            name='course_req_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_result_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
