# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0005_auto_20160806_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avability_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='avability_end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='avability_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='avability_start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
