# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0007_auto_20160811_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='webinar_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_is_free',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_max_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_price_per_access',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='webinar_subsequent_ed',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
