# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0008_auto_20160811_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_is_free',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_subsequent_ed',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
