# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0009_auto_20160811_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_course', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
