# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160724_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_successrate',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
