# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160801_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_description',
            new_name='user_desc',
        ),
    ]
