# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20160801_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
